services:
  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_REPLICA_ID=rs0
      - MONGO_REPLICA_HOST_PRIMARY=mongo-db
    container_name: mongo-primary
    ports:
      - "27017:27017"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0"
      ]
    volumes:
      - ./rs-init.sh:/scripts/rs-init.sh
  node:
    image: jhordyess/node
    depends_on:
      - mongo-db
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "4062:4062"
    environment:
      - DATABASE_URL
    volumes:
      - .:/mern-crud-project:cached
